export const NAME_LIST: readonly string[] = [
    'April Middleton',
    'Aubrey Gill',
    'Barry Coleridge',
    'Benjamin Morales Benjamin Morales Benjamin Morales Benjamin Morales Benjamin Morales Benjamin Morales',
    'Cade Sarratt',
    'Chris Patton',
    'Eden Presley',
    'Emily Cole',
    'Garrick Arnold',
    'Gilbert Harris',
    'Ingram Nichols',
    'Josephine Marsh',
    'June Franklin',
    'Kim Anne',
    'Leo Ulysses',
    'Maynard Clayton',
    'Page Hume',
    'Phyllis Roland',
    'Ralap',
    'Rosalind Hartley',
    'Shawn Hampton',
    'Sherry',
    'Taylor Black',
    'Trina Hall',
    'Ulric Skeldon',
    'Cade Sarratt2',
    'Chris Patton2',
    'Eden Presley2',
    'Emily Cole2',
    'Garrick Arnold2',
    'Gilbert Harris2',
    'Ingram Nichols2',
    'Josephine Marsh2',
    'June Franklin2',
    'Kim Anne2',
    'Leo Ulysses2',
    'Maynard Clayton2',
    'Page Hume2',
    'Phyllis Roland2',
    'Ralap2',
    'Rosalind Hartley2',
    'Shawn Hampton2',
    'Sherry2',
    'Taylor Black2',
    'Trina Hall2',
    'Ulric Skeldon2',
    'Cade Sarratt3',
    'Chris Patton3',
    'Eden Presley3',
    'Emily Cole3',
    'Garrick Arnold3',
    'Gilbert Harris3',
    'Ingram Nichols3',
    'Josephine Marsh3',
    'June Franklin3',
    'Kim Anne3',
    'Leo Ulysses3',
    'Maynard Clayton3',
    'Page Hume3',
    'Phyllis Roland3',
    'Ralap3',
    'Rosalind Hartley3',
    'Shawn Hampton3',
    'Sherry3',
    'Taylor Black3',
    'Trina Hall3',
    'Ulric Skeldon3',
]

export interface User {
    readonly name: string
    readonly age: number
}

export const USER_LIST: readonly User[] = [
    {name: 'zhangsan', age: 21},
    {name: 'lisi', age: 22},
    {name: 'wangwu', age: 24},
    {name: 'zhaoliu', age: 23},
]

export interface UserGroup {
    readonly name: string
    readonly users: readonly User[]
}

export const USER_GROUP_LIST: readonly UserGroup[] = [
    {
        name: '一组',
        users: [
            {name: 'zhangsan', age: 21},
            {name: 'lisi', age: 22},
            {name: 'Cade Sarratt', age: 22},
            {name: 'Chris Patton', age: 22},
            {name: 'Eden Presley', age: 22},
            {name: 'Emily Cole', age: 22},
            {name: 'Garrick Arnold', age: 22},
            {name: 'Kim Anne', age: 22},
            {name: 'Leo Ulysses', age: 22},
            {name: '2zhangsan', age: 21},
            {name: '2lisi', age: 22},
            {name: '2Cade Sarratt', age: 22},
            {name: '2Chris Patton', age: 22},
            {name: '2Eden Presley', age: 22},
            {name: '2Emily Cole', age: 22},
            {name: '2Garrick Arnold', age: 22},
            {name: '2Kim Anne', age: 22},
            {name: '2Leo Ulysses', age: 22},
        ],
    },
    {
        name: '二组',
        users: [
            {name: 'wangwu', age: 24},
            {name: 'zhaoliu', age: 23},
            {name: 'Gilbert Harris', age: 22},
            {name: 'Ingram Nichols', age: 22},
            {name: 'Josephine Marsh', age: 22},
            {name: 'June Franklin', age: 22},
            {name: '2wangwu', age: 24},
            {name: '2zhaoliu', age: 23},
            {name: '2Gilbert Harris', age: 22},
            {name: '2Ingram Nichols', age: 22},
            {name: '2Josephine Marsh', age: 22},
            {name: '2June Franklin', age: 22},
        ],
    },
    {
        name: '三组',
        users: [
            {name: 'qianqi', age: 24},
            {name: 'sunba', age: 23},
            {name: 'Ralap', age: 22},
            {name: 'Rosalind Hartley', age: 22},
            {name: 'Shawn Hampton', age: 22},
            {name: 'Maynard Clayton', age: 22},
            {name: 'Page Hume', age: 22},
            {name: 'Phyllis Roland', age: 22},
            {name: 'Sherry', age: 22},
            {name: '2qianqi', age: 24},
            {name: '2sunba', age: 23},
            {name: '2Ralap', age: 22},
            {name: '2Rosalind Hartley', age: 22},
            {name: '2Shawn Hampton', age: 22},
            {name: '2Maynard Clayton', age: 22},
            {name: '2Page Hume', age: 22},
            {name: '2Phyllis Roland', age: 22},
            {name: '2Sherry', age: 22},
        ],
    },
]
